#!/usr/bin/env python
from optparse import OptionParser
from parseDictionary import dictionary
import os,sys

if __name__ == '__main__':
    usage = "Usage: %prog [options] word"
    parser = OptionParser(usage=usage)
    (options, args) = parser.parse_args()
    pwd = os.path.split(os.path.realpath(sys.argv[0]))[0]

    dictionary = dictionary(pwd)
    for word in args:
        dictionary.search(word)
        pass
 
