#!/usr/bin/env python
from optparse import OptionParser
from parseDictionary import dictionary

if __name__ == '__main__':
	usage = "Usage: %prog [options] word"
	parser = OptionParser(usage=usage)
	(options, args) = parser.parse_args()

	dictionary = dictionary()
	for word in args:
		dictionary.search(word)
		pass
 
