#!/usr/bin/env python
from optparse import OptionParser

def wd_help():
	print "Hello World!"
	pass

def wd_del_option():
	parser = OptionParser()
	#parser.add_option("-h","--help",dest="",help="help info",metavar="FILE")
	parser.parse_args()
	pass

if __name__ == '__main__':
	wd_del_option()


